### ISSUE TITLE
XML namespace name

### ISSUE THREAD

**Issue by farski** [syndicated-media/sn-spec#54]
#11 has a good discussion about the namespace tag prefix we want to use in XML tags (even though technically it's largely unimportant if #53 is honored). Before we pick something to standardize around in docs and examples, we need to figure out the _namespace name_ (the URL; namespace name is the W3C term) that actually identifies the namespace.

@Cj-Malone threw out `https://www.syndicated.media/schema/1.0/` and `https://www.syndicated.media/schema/sm/1.0/`

I don't love the idea of including `sm` or whatever tag prefix we land on in the namespace name. I guess it's a question of whether we think we'll ever publish multiple distinct namespaces under the syndicated.media banner. I would be in favor of something more abstract, like a simple incremental id.

eg `https://schema.syndicated.media/A/1.0/`

and if later we need `https://schema.syndicated.media/A/1.7/` or ``https://schema.syndicated.media/B/1.0/`` that might be fine.

**Comment by cqr** [comment]
Would we consider using https://w3id.org? It may not be necessary, important, or even helpful, but to me it feels like it is the typical way to go for standards that are not controlled by a single company to use a service like this.

Beyond that I would be bikeshedding.

**Comment by cio-blubrry** [comment]
`sm`  is ideal, minimal characters which is a plus.

I would not point the URL to syndicated.media until the domain name is registered under a public entity rather than an individual, assuming the public entity is an organization that manages this syndicated media namespace.

**Comment by farski** [comment]
@cio-blubrry the XML namespace name needs to be a URI and is almost always a URL, so `sm` probably isn't a great options

**Comment by cqr** [comment]
@cio-blubrry does using w3id.org as I suggested address those concerns?

**Comment by cio-blubrry** [comment]
@chrisrhoden  yea, but I see value in having it under the same domain name as the documentation. Would we then put the documentation on w3id.org as well?

**Comment by cqr** [comment]
@cio-blubrry w3id.org is primarily a redirection service for these types of URIs, so we would be able to point the namespace URI at the documentation wherever it was hosted (even if that was still on github)

**Comment by kookster** [comment]
I'm reading up on w3id.org, but I like it notionally

**Comment by kookster** [comment]
ok, it makes sense to me to use w3id.org - seems like it is made to order for this purpose

Given the suggested standard:
`https://w3id.org/PROJECT-ID/SUB-ID...`

Seems like we could start with something like this for the base project:

  `https://w3id.org/syndicated-media/` 

(I am suggesting changing the '.' to a '-' because that is more standard for a url path.)

And then add schema and version number on there as a sub project namespace for schema URIs:

  `https://w3id.org/syndicated-media/schema/1.0`

If we had a sub-schema with its own name and versioning (e.g. just tags related to curated collections), we could use something like this:

  `https://w3id.org/syndicated-media/schema/collections/1.0`

Is that feasible and desirable?

**Comment by kookster** [comment]
as far as the `PROJECT-ID`, I do see all manner of compound word representations in the https://github.com/perma-id/w3id.org repo eg.
- `schema.org`
- `activity-streams`
- `linkedEarth`

So it seems like there is not a strong standard in place. I still like `https://w3id.org/syndicated-media/`, but I am a 1 out of 5 on snake case `syndicated-media` vs. camel case vs. the host 'syndicated.media`

**Comment by cio-blubrry** [comment]
I would prefer a unique domain that has all the documentation and a welcome home page that way it is all wrapped together which will make it easier for someone to take seriously who visit the link when they see it in their browser or application. This is deep in the weeds but you will have random users who may or may not be tech savvy who find the URL in the feed's XML. They will form an opinion on the said link and its meaning based on their experience visiting the website. Just something to keep in mind.

**Comment by kookster** [comment]
So @cio-blubrry you are suggesting using syndicated.media in the xmlns declaration instead of w3id.org redirecting to syndicated.media?

**Comment by cio-blubrry** [comment]
Yes.

Redirecting is not professional and puts doubt into the user who follows the link. Though you may know that every link that goes to w3id.org is well vetted and reputable, most will be suspect of a redirect from one domain to another.

**Comment by theDanielJLewis** [comment]
I also agree that this should be on its own, branded domain.

**Comment by cqr** [comment]
I would be in favor of using a custom domain, as long as you no longer feel that we need to literally form a company in order to do so.

w3id.org is the successor to purl.org, where many community controlled RSS extensions were published. I'm willing to wager you have a purl.org namespace or two in all of your feeds. The use of a system like it is common in these circles.

**Comment by kookster** [comment]
I probably am slightly more in favor of having the branded domain with docs and welcome homepage at syndicated.media, but use a w3id.org address in the xmlns for the permanence and separation from the destiny any one company/org.

That said, like @chrisrhoden, I like syndicated.media as a domain, so long as @farski pinky swears to not do anything terrible with it while governance is still being figured out, and that's good enough with everyone for now.

**Comment by farski** [comment]
The committee has decided on `https://schema.syndicated.media/core/1.0/` as the first namespace name that will use for extending RSS 2.0

**Comment by cio-blubrry** [comment]
Sorry, I must have missed a meeting. Last time we discussed were were still debating on creating an organization with committees. Who are the members of this new committee and what is the committee's name and objectives?

**Comment by farski** [comment]
We came up with the plan to try forming small committees to finalize specs on the last video call. It was also announced on [Slack](https://syndicated-media.slack.com/archives/general/p1487357281000912). The committee has no formal name, and the objective was to pick a namespace name that satisfied the needs identified in this issue.

**Comment by cio-blubrry** [comment]
If you have a calendar when all future meetings are going to take place I would love to add that to my calendar (I am sure others do too).

I searched slack for this announcement, I searched for 'video' the only meeting I could find was announced 4 hours before it took place on February 15th. I scrolled from Feb 15th and did not see any other meeting announcements up through today. I was on that call on the 15th. I do not recall any vote that day, just items discussed. I do recall though someone had a very poor argument for not creating an organization near the end of the call, which ended with what appeared to me as a consensus that we should form some sort of organization before moving forward.

I do not understand how you can have a committee without a name or purpose. I mentioned before the importance of having an organization with leadership elected by its members and committees for specific tasks that work within a set of rules that represent everyone involved.  If you want an example why this is important, please look back at the Association for Downloadable Media, a previous trade organization for podcasting from 2006-2009. That group actually was an incorporated non-profit, but it did not follow the Roberts Rules of Order once it was setup and had no set guidelines for how members were to work within the organization which lead to crazy agendas, most podcasters were left out of the conversations, and ended with Volo Media using the website and mailing list as a launching pad to announce their intent to enforce their patent on podcasting. Until leaders of this group create some sort of organization with voted leadership by its members, rules how votes are counted and decisions are made, etc..., the current trajectory of this group is failure. I fail to see how Apple would take any new specs in RSS seriously without organized membership with documented meetings of a well rounded committee members and board leadership to back it up. I am sure the intentions of this group may be good but the work here will most likely go nowhere outside of those who are pushing the current agendas without any organized governing involved.

**Comment by israelroldan** [comment]
@cio-blubrry There was a channel wide announcement in #general on January 19th 
<img width="602" alt="screen shot 2017-03-08 at 09 59 10" src="https://cloud.githubusercontent.com/assets/159962/23696958/2384d03c-03e6-11e7-858c-2303b7870bec.png">
Just search for "call" instead of "video".
