### ISSUE TITLE
A spec for guests

### ISSUE THREAD

**Issue by hellosteadman** [syndicated-media/sn-spec#59]
For a long time I've wanted a standardised way of marking up the guests that appear on a specific episode. Perhaps using the foaf namespace would work? Thinking it would be good to allow links to multiple sites per guest, so their social networking details can be listed as well as a link to their blog - or their own podcast.

Clients would then be able to list this info alongside the show notes, but as we would be likely to include that info in the snow notes anyway, I think it's probably more useful as a way of contributing metadata to an overall index, and allowing easy traversal through podcasts, along the lines of "if you liked this guest, you might like their podcast".

Any thoughts?

**Comment by farski** [comment]
I think this general idea may already be covered by #17. The idea of having structured external resources is interesting, but I worry it may be biting off a lot for an addition like this right out of the gate. The last thing you mentioned feels more like #28.
